services:
  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Set to true if you have a connection string set in .env:
      - APPLICATIONINSIGHTS_ENABLED=false
      # Enables External ID login/logout flow locally. Set additional configs in .env:
      - PETSTORE_SECURITY_ENABLED=false
      - PETSTOREORDERITEMSRESERVER_URL=http://petstoreorderitemsreserver:80

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGPETDATABASE:-petstorepetservice_db}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=${PGSSLMODE:-require}

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT:-5432}
      - PGDATABASE=${PGPRODUCTDATABASE:-petstoreproductservice_db}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGSSLMODE=${PGSSLMODE:-require}

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    env_file:
      - .env

  petstoreorderitemsreserver:
    build:
      context: ./petstoreorderitemsreserver
    ports:
      - "8085:80"
    env_file:
      - .env
    environment:
      - AzureWebJobsStorage=
      - BLOB_STORAGE_CONNECTION_STRING=${BLOB_STORAGE_CONNECTION_STRING}
      - BLOB_STORAGE_CONTAINER_NAME=orderitemsreserver